### ISSUE TITLE
displacement sphere code is removed.

### ISSUE THREAD

**Issue by onethree-13** [ramakarl/just_math#33]
Hi,
I saw your post [ray tracing a sphere with displacement mapping](https://stackoverflow.com/questions/4476669/ray-tracing-a-sphere-with-displacement-mapping), but cannot find the math_displace_sphere sample in this repo. 
Could you please modify the answer and add the correct link?

**Comment by ramakarl** [comment]
For now I have restored the math_displace_sphere folder in the just_math repository:
  https://github.com/ramakarl/just_math/tree/main/math_displace_sphere
This might be moved to a separate repo in the future.

-R
